### ISSUE TITLE
New Fail reported after Fontbakery 0.7.35 version

### ISSUE THREAD

**Issue by vv-monsalve** [xotypeco/big_shoulders#35]
HI @xotypeco, Fontbakery has now a new version and there is a new Fail reported for the all the fonts (both VF + statics) in all the families:

<details>
<summary>🔥 <b>FAIL:</b> Ensure Stylistic Sets have description.</summary>

* [com.google.fonts/check/stylisticset_description](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/stylisticset_description)
<pre>--- Rationale ---
Stylistic sets must provide description text. Programs such as InDesign,
TextEdit and Inkscape use that info to display to the users so that they know
what a given stylistic set offers.</pre>

* 🔥 **FAIL** The stylistic set ss01 lacks a description string on the 'name' table. [code: missing-description]

</details>

**Comment by xotypeco** [comment]
hi—.ss01 has more contemporary forms in three characters—a straight-legged R, an a with an open loop & an open-bowl g. 

I don't know where this description happens, though. should you add this description, since you're pulling new masters?

<img width="858" alt="Screen Shot 2021-05-13 at 8 18 03 AM" src="https://user-images.githubusercontent.com/52611676/118131455-27f10180-b3c4-11eb-9b3d-09d339070a24.png">

**Comment by vv-monsalve** [comment]
We are asking this Fail to be downgraded to a Warn as it is not something that actually broken in the font.
Are you going to change anything in the sources for the Vietnamese or diagonal letters?

**Comment by xotypeco** [comment]
> We are asking this Fail to be downgraded to a Warn as it is not something that actually broken in the font.

👍🏻

> Are you going to change anything in the sources for the Vietnamese or diagonal letters?

already done!

**Comment by vv-monsalve** [comment]
> already done!

Great! Didn't know if you wanted to change anything after the last images.
